export const apiUrl = "http://localhost:4000/api";

export const LOCAL_STORAGE_TOKEN_NAME = "ppn-user";
export const SET_AUTH = "SET_AUTH";


// Customer
export const CUSTOMERS_LOADED_SUCCESS = "CUSTOMERS_LOAD_SUCCESS";
export const CUSTOMERS_LOADED_ERROR = "CUSTOMERS_LOAD_ERROR";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const FIND_CUSTOMER = "FIND_CUSTOMER";

// trash
export const CUSTOMERS_TRASH_LOADED_SUCCESS = "CUSTOMERS_TRASH_LOAD_SUCCESS";
export const CUSTOMERS_TRASH_LOADED_ERROR = "CUSTOMERS_TRASH_LOAD_ERROR";
export const DESTROY_CUSTOMER = "DESTROY_CUSTOMER";
export const RESTORE_CUSTOMER = "RESTORE_CUSTOMER";

